# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "923a2370d32ef8ec9424ed8ab53e8bd0"
name = "shipping-cost-calculator"
handle = "shipping-cost-calculator-1"
application_url = "https://3.76.235.152"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_shipping"

[auth]
redirect_urls = [
  "https://3.76.235.152/auth/callback",
  "https://3.76.235.152/auth/shopify/callback",
  "https://3.76.235.152/api/auth/callback"
]

[pos]
embedded = false
