# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "923a2370d32ef8ec9424ed8ab53e8bd0"
name = "shipping-cost-calculator"
handle = "shipping-cost-calculator-1"
application_url = "https://encyclopedia-obesity-bradford-bhutan.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_shipping"

[auth]
redirect_urls = [
  "https://encyclopedia-obesity-bradford-bhutan.trycloudflare.com/auth/callback",
  "https://encyclopedia-obesity-bradford-bhutan.trycloudflare.com/auth/shopify/callback",
  "https://encyclopedia-obesity-bradford-bhutan.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
